### ISSUE TITLE
Unit creation failing: Error 1048: Column 'description' cannot be null

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#109]
I believe this is occurring in the procedure: `unit_create_with_dummy_users` in https://github.com/unee-t/bz-database/blob/master/db%20snapshots/unee-t_BZDb_clean_current.sql
.... but I don't know what table.

It's not the products table since description seems to be set there fine.

**Comment by kaihendry** [comment]
Btw the procedure is called from the unit API https://github.com/unee-t/unit/blob/master/sql/unit_create_new.sql

**Comment by franck-boullier** [comment]
OK I think I understand what's happening there...

This is a problem which is very specific to our DEV/Staging environment and which should not happen for any fresh install.

We have pre-defined dummy users in each environment. These are important because they're needed to create units initially.

These users are identified by user id in the `profiles` table in the database.
The PROD and DEV/Staging had these 'dummy' users created after existing users so their user ids are different from a fresh install.

The quick fix should be to restore the profile related information for the DEV/Staging from a backup (I'll do that) and test that all is working as expected.

The longer/more complex thing to do would be to alter the scripts but this might take some time and I see no real value in that TBH: I prefer to have the ability to retain all the DEV/Staging users credentials after a restore even if all the units and cases are wipped out (feel free to correct me if I'm wrong there)

**Comment by franck-boullier** [comment]
@kaihendry can you test again? (you might have to create a new user or use an old user that was working before the restore

**Comment by franck-boullier** [comment]
another solution that should work if we want to do a fresh install in the DEV/staging from the clean BZFE database would be to use the environment parameter = 3 (demo/dev) instead of the environment parameter = 1 (DEV/Staging) when we have to trigger the lambdas (this might be more complex than restoring the pre-existing users though - happy to discuss options there)

**Comment by kaihendry** [comment]
![screenshot 2019-02-04 at 1 29 55 pm](https://user-images.githubusercontent.com/765871/52191705-09187200-2881-11e9-8663-8a176277fdf2.png)

```
  Feb 4th 01:30:10pm INFO production 0e03287 Running unit_create_new.sql with unit id J1IJIlPy3293lvUiX with env 1
  Feb 4th 01:30:10pm ERRO production 0e03287 unit_create_new.sql failed: error=Error 1048: Column 'name' cannot be null reqid=ef0b450f-283d-11e9-9cc5-19ec32d78a5d unit=map[bzfe_creator_user_id:3469 classification_id:2 mefe_creator_user_id:XTRijwWSmjcL65YhG mefe_unit_id:J1IJIlPy3293lvUiX unit_description_details:HALLO unit_name:NewTest2]
  Feb 4th 01:30:10pm WARN production 0e03287 response: duration=145ms id=ef0b450f-283d-11e9-9cc5-19ec32d78a5d ip=13.250.114.3 method=POST path=/create size=41 B status=400
```

**Comment by franck-boullier** [comment]
# Debugging:
There is no product in the BZFE yet.
When the script creates a unit it needs to have at least 1 product in the product table.
Why?
Because the name of the newly created product will be derived from the highest `product_id` in the `products` table.
The formula is new product_id = (SELECT MAX(`id`) FROM `products` +1)
BUT
from a MySQL perspective NULL + 1 (or anything for that matter) = NULL
when we concat the 2 information "unit name entered by the user" + "new product id" to get the BZFE name for the new unit (we need to do that for various reasons then MySQL does CONCAT ("somethin" and NULL) and the result is NULL ---> as far as the DB engine is concerned name is NULL and this is not allowed ---> error

Short term fix: Make sure you always have at least 1 product in the product table before trying to create a new unit via the MEFE

@kaihendry can you test that please (try again with the test unit still there)?

**Comment by kaihendry** [comment]
Going to defer to https://github.com/unee-t/bz-database/issues/111
