### ISSUE TITLE
Use transactions

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#95]
After chatting with https://twitter.com/dylan_hardison there are a couple of things he pointed out. Even if the procedure is wrapped in a transaction, things like **CREATE TABLE** as listed upon https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html will break out of that transaction.

That's why there are constructs like https://dev.mysql.com/doc/refman/8.0/en/create-temporary-table.html that we should be using instead of:

```
# Re-create the temp table
		CREATE TABLE `ut_user_group_map_temp` (
		  `user_id` MEDIUMINT(9) NOT NULL,
		  `group_id` MEDIUMINT(9) NOT NULL,
		  `isbless` TINYINT(4) NOT NULL DEFAULT '0',
		  `grant_type` TINYINT(4) NOT NULL DEFAULT '0'
		) ENGINE=INNODB DEFAULT CHARSET=utf8;
		# Add all the records that exists in the table user_group_map
		INSERT INTO `ut_user_group_map_temp`
			SELECT *
			FROM `user_group_map`;
```

Otherwise I am trying to evaluate whether transactions should be performed in SQL via https://dev.mysql.com/doc/refman/8.0/en/declare-handler.html or the [Golang Mysql driver](https://github.com/go-sql-driver/mysql#usage).

**Comment by kaihendry** [comment]
I am not 100% sure if transactions help. I think they might: https://youtu.be/3aDLnQ4-yc8

**Comment by franck-boullier** [comment]
I think part of the solution to avoid the race condition issue in some extreme scenario is to:
1-  use temp table to do the deduplication 
and 
2- also use the [LAST INSERT ID() ](https://dev.mysql.com/doc/refman/8.0/en/getting-unique-id.html) function from mysql to capture the id after the objects are created.

Because it is maintained in the server on a per-connection basis. It is not changed by another client so simultaneous execution of the procedure will work as intended.

I'll have a crack at this fix later during the WE.

The main problem we have as far as I can understand is the timeout issue with lambda ---> transaction does indeed seem to be the right path forward

**Comment by kaihendry** [comment]
IIRC https://github.com/unee-t/invite/ was fixed by https://github.com/unee-t/bz-database/commit/2c11a4eb751b23631a652d4465d52c5635c4ce2a
